name: Tests
on: [workflow_dispatch, push]
jobs:
  test_basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: run_moss
        uses: ./
        with:
          user_id: ${{ secrets.MOSS_USER_ID }}
          arguments: -l python test_data/basic/main.py
      - run: echo 'MOSS Report URL = ${{ steps.run_moss.outputs.url }}'